# NEXORA Linux Kernel Configuration
# Target: x86_64

CONFIG_64BIT=y
CONFIG_X86_64=y
CONFIG_X86=y

CONFIG_SMP=y
CONFIG_MODULES=y
CONFIG_MODULE_UNLOAD=y

CONFIG_BINFMT_ELF=y
CONFIG_BINFMT_SCRIPT=y

CONFIG_DEVTMPFS=y
CONFIG_DEVTMPFS_MOUNT=y

CONFIG_PROC_FS=y
CONFIG_SYSFS=y
CONFIG_TMPFS=y
CONFIG_TMPFS_POSIX_ACL=y

CONFIG_EXT4_FS=y
CONFIG_VFAT_FS=y
CONFIG_ISO9660_FS=y
CONFIG_SQUASHFS=y

CONFIG_BLK_DEV=y
CONFIG_BLK_DEV_LOOP=y

CONFIG_NET=y
CONFIG_INET=y
CONFIG_UNIX=y

CONFIG_TTY=y
CONFIG_VT=y
CONFIG_VT_CONSOLE=y

CONFIG_INPUT=y
CONFIG_SERIAL_8250=y
CONFIG_SERIAL_8250_CONSOLE=y

CONFIG_PCI=y
CONFIG_PCI_MSI=y

CONFIG_EFI=y
CONFIG_EFI_STUB=y

CONFIG_ACPI=y

CONFIG_USB_SUPPORT=y
CONFIG_USB=y
CONFIG_USB_STORAGE=y

CONFIG_SCSI=y
CONFIG_BLK_DEV_SD=y

CONFIG_OVERLAY_FS=y

# Security
CONFIG_SECURITY=y
CONFIG_SECURITYFS=y

# Containers / namespaces
CONFIG_NAMESPACES=y
CONFIG_UTS_NS=y
CONFIG_IPC_NS=y
CONFIG_PID_NS=y
CONFIG_NET_NS=y
CONFIG_CGROUPS=y
CONFIG_CGROUP_CPUACCT=y
CONFIG_CGROUP_DEVICE=y
CONFIG_CGROUP_FREEZER=y
CONFIG_CGROUP_SCHED=y

# NEXORA
