# NEXORA Root Filesystem Configuration

ROOTFS_NAME="NEXORA Linux"
ROOTFS_ARCH="x86_64"

ROOTFS_DIR="nexora/rootfs"

ROOTFS_DIRS="
etc
bin
sbin
usr/bin
usr/sbin
var
tmp
dev
proc
sys
run
home
root
"

ROOTFS_INIT="/sbin/init"
