#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mount -t tmpfs tmpfs /run

echo "================================"
echo "       NEXORA Linux"
echo "================================"
echo "NEXORA initramfs started."
echo "NEXORA_BOOT_OK"

exec /bin/sh
