name: Runner Test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  runner-test:
    runs-on: ubuntu-latest
    steps:
      - name: Test GitHub Runner
        run: |
          echo "GITHUB_RUNNER_OK"
          uname -a
          date
